# Generated by Django 3.2 on 2021-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0002_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SreviceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
